[package]
name = "tweeq-egui"
description = "Tweeq parameter-tuning widgets for egui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/tweeq-egui"
readme = "README.md"
keywords = ["egui", "gui", "widgets", "parameter", "creative-tools"]
categories = ["gui"]

[dependencies]
egui.workspace = true
tweeq-core.workspace = true

[lints]
workspace = true
